/**
 * GmodStore API
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AdventCalendarStatsResponse from '../model/AdventCalendarStatsResponse';
import ErrorResponse from '../model/ErrorResponse';

/**
* AdventCalendar service.
* @module Everyday/GmodStore/Sdk/api/AdventCalendarApi
* @version 1.2.0
*/
export default class AdventCalendarApi {

    /**
    * Constructs a new AdventCalendarApi. 
    * @alias module:Everyday/GmodStore/Sdk/api/AdventCalendarApi
    * @class
    * @param {module:Everyday/GmodStore/Sdk/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:Everyday/GmodStore/Sdk/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAdventCalendarStats operation.
     * @callback module:Everyday/GmodStore/Sdk/api/AdventCalendarApi~getAdventCalendarStatsCallback
     * @param {String} error Error message, if any.
     * @param {module:Everyday/GmodStore/Sdk/model/AdventCalendarStatsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Fetch statistics relating to the advent calendar event
     * @param {module:Everyday/GmodStore/Sdk/api/AdventCalendarApi~getAdventCalendarStatsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:Everyday/GmodStore/Sdk/model/AdventCalendarStatsResponse}
     */
    getAdventCalendarStats(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AdventCalendarStatsResponse;
      return this.apiClient.callApi(
        '/events/advent-calendar/stats', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
