/**
 * GmodStore API
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Addon from './Addon';

/**
 * The AddonListResponse model module.
 * @module Everyday\GmodStore\Sdk/model/AddonListResponse
 * @version 1.1.0
 */
class AddonListResponse {
    /**
     * Constructs a new <code>AddonListResponse</code>.
     * @alias module:Everyday\GmodStore\Sdk/model/AddonListResponse
     */
    constructor() { 
        
        AddonListResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddonListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday\GmodStore\Sdk/model/AddonListResponse} obj Optional instance to populate.
     * @return {module:Everyday\GmodStore\Sdk/model/AddonListResponse} The populated <code>AddonListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddonListResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Addon]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:Everyday\GmodStore\Sdk/model/Addon>} data
 */
AddonListResponse.prototype['data'] = undefined;






export default AddonListResponse;

