/**
 * GmodStore API
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AddonStatsRevenue from './AddonStatsRevenue';
import AddonStatsSales from './AddonStatsSales';
import AddonStatsViews from './AddonStatsViews';

/**
 * The AddonStats model module.
 * @module Everyday/GmodStore/Sdk/model/AddonStats
 * @version 1.3.2
 */
class AddonStats {
    /**
     * Constructs a new <code>AddonStats</code>.
     * @alias module:Everyday/GmodStore/Sdk/model/AddonStats
     */
    constructor() { 
        
        AddonStats.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddonStats</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday/GmodStore/Sdk/model/AddonStats} obj Optional instance to populate.
     * @return {module:Everyday/GmodStore/Sdk/model/AddonStats} The populated <code>AddonStats</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddonStats();

            if (data.hasOwnProperty('revenue')) {
                obj['revenue'] = AddonStatsRevenue.constructFromObject(data['revenue']);
            }
            if (data.hasOwnProperty('views')) {
                obj['views'] = AddonStatsViews.constructFromObject(data['views']);
            }
            if (data.hasOwnProperty('sales')) {
                obj['sales'] = AddonStatsSales.constructFromObject(data['sales']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Everyday/GmodStore/Sdk/model/AddonStatsRevenue} revenue
 */
AddonStats.prototype['revenue'] = undefined;

/**
 * @member {module:Everyday/GmodStore/Sdk/model/AddonStatsViews} views
 */
AddonStats.prototype['views'] = undefined;

/**
 * @member {module:Everyday/GmodStore/Sdk/model/AddonStatsSales} sales
 */
AddonStats.prototype['sales'] = undefined;






export default AddonStats;

