/**
 * gmodstore
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # Rate limits Every request you make to the GmodStore API will count against your rate limit, which at the time of writing this, is 60 requests / minute. An up-to-date value will always provided in the `X-RateLimit-Limit` header The number of requests you have remaining before you must wait is provided in the `X-RateLimit-Remaining` header.  # API SDKs For a list of available API SDKs check the README here: https://github.com/everyday-as/gmodstore-api-docs#client-libraries
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConnectionPaginatedCursors from './ConnectionPaginatedCursors';
import ConnectionPaginatedMeta from './ConnectionPaginatedMeta';

/**
 * The ConnectionPaginated model module.
 * @module Everyday/GmodStore/Sdk/model/ConnectionPaginated
 * @version 3.1.0
 */
class ConnectionPaginated {
    /**
     * Constructs a new <code>ConnectionPaginated</code>.
     * @alias module:Everyday/GmodStore/Sdk/model/ConnectionPaginated
     * @param cursors {module:Everyday/GmodStore/Sdk/model/ConnectionPaginatedCursors} 
     * @param connections {Array.<String>} 
     * @param meta {module:Everyday/GmodStore/Sdk/model/ConnectionPaginatedMeta} 
     */
    constructor(cursors, connections, meta) { 
        
        ConnectionPaginated.initialize(this, cursors, connections, meta);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cursors, connections, meta) { 
        obj['cursors'] = cursors;
        obj['connections'] = connections;
        obj['meta'] = meta;
    }

    /**
     * Constructs a <code>ConnectionPaginated</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday/GmodStore/Sdk/model/ConnectionPaginated} obj Optional instance to populate.
     * @return {module:Everyday/GmodStore/Sdk/model/ConnectionPaginated} The populated <code>ConnectionPaginated</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConnectionPaginated();

            if (data.hasOwnProperty('cursors')) {
                obj['cursors'] = ConnectionPaginatedCursors.constructFromObject(data['cursors']);
            }
            if (data.hasOwnProperty('connections')) {
                obj['connections'] = ApiClient.convertToType(data['connections'], ['String']);
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = ConnectionPaginatedMeta.constructFromObject(data['meta']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:Everyday/GmodStore/Sdk/model/ConnectionPaginatedCursors} cursors
 */
ConnectionPaginated.prototype['cursors'] = undefined;

/**
 * @member {Array.<String>} connections
 */
ConnectionPaginated.prototype['connections'] = undefined;

/**
 * @member {module:Everyday/GmodStore/Sdk/model/ConnectionPaginatedMeta} meta
 */
ConnectionPaginated.prototype['meta'] = undefined;






export default ConnectionPaginated;

