/**
 * GmodStore API
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewAddonPurchase model module.
 * @module Everyday/GmodStore/Sdk/model/NewAddonPurchase
 * @version 1.2.3
 */
class NewAddonPurchase {
    /**
     * Constructs a new <code>NewAddonPurchase</code>.
     * @alias module:Everyday/GmodStore/Sdk/model/NewAddonPurchase
     * @param userId {Number} 
     */
    constructor(userId) { 
        
        NewAddonPurchase.initialize(this, userId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId) { 
        obj['user_id'] = userId;
    }

    /**
     * Constructs a <code>NewAddonPurchase</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday/GmodStore/Sdk/model/NewAddonPurchase} obj Optional instance to populate.
     * @return {module:Everyday/GmodStore/Sdk/model/NewAddonPurchase} The populated <code>NewAddonPurchase</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewAddonPurchase();

            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} user_id
 */
NewAddonPurchase.prototype['user_id'] = undefined;






export default NewAddonPurchase;

