/**
 * gmodstore
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # Rate limits Every request you make to the GmodStore API will count against your rate limit, which at the time of writing this, is 60 requests / minute. An up-to-date value will always provided in the `X-RateLimit-Limit` header The number of requests you have remaining before you must wait is provided in the `X-RateLimit-Remaining` header.  # API SDKs For a list of available API SDKs check the README here: https://github.com/everyday-as/gmodstore-api-docs#client-libraries
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Money from './Money';

/**
 * The OrderItem model module.
 * @module Everyday/GmodStore/Sdk/model/OrderItem
 * @version 3.1.0
 */
class OrderItem {
    /**
     * Constructs a new <code>OrderItem</code>.
     * @alias module:Everyday/GmodStore/Sdk/model/OrderItem
     * @param id {String} 
     * @param price {module:Everyday/GmodStore/Sdk/model/Money} 
     * @param reversedAt {Date} 
     */
    constructor(id, price, reversedAt) { 
        
        OrderItem.initialize(this, id, price, reversedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, price, reversedAt) { 
        obj['id'] = id;
        obj['price'] = price;
        obj['reversedAt'] = reversedAt;
    }

    /**
     * Constructs a <code>OrderItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday/GmodStore/Sdk/model/OrderItem} obj Optional instance to populate.
     * @return {module:Everyday/GmodStore/Sdk/model/OrderItem} The populated <code>OrderItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderItem();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = Money.constructFromObject(data['price']);
            }
            if (data.hasOwnProperty('reversedAt')) {
                obj['reversedAt'] = ApiClient.convertToType(data['reversedAt'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
OrderItem.prototype['id'] = undefined;

/**
 * @member {module:Everyday/GmodStore/Sdk/model/Money} price
 */
OrderItem.prototype['price'] = undefined;

/**
 * @member {Date} reversedAt
 */
OrderItem.prototype['reversedAt'] = undefined;






export default OrderItem;

