/**
 * gmodstore
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # Rate limits Every request you make to the GmodStore API will count against your rate limit, which at the time of writing this, is 60 requests / minute. An up-to-date value will always provided in the `X-RateLimit-Limit` header The number of requests you have remaining before you must wait is provided in the `X-RateLimit-Remaining` header.  # API SDKs For a list of available API SDKs check the README here: https://github.com/everyday-as/gmodstore-api-docs#client-libraries
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PersonalAccessTokenScope from './PersonalAccessTokenScope';

/**
 * The PersonalAccessToken model module.
 * @module Everyday/GmodStore/Sdk/model/PersonalAccessToken
 * @version 3.1.0
 */
class PersonalAccessToken {
    /**
     * Constructs a new <code>PersonalAccessToken</code>.
     * @alias module:Everyday/GmodStore/Sdk/model/PersonalAccessToken
     * @param id {String} 
     * @param name {String} 
     * @param abilities {Array.<module:Everyday/GmodStore/Sdk/model/PersonalAccessTokenScope>} 
     * @param lastUsedAt {Date} 
     * @param expiresAt {Date} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     */
    constructor(id, name, abilities, lastUsedAt, expiresAt, createdAt, updatedAt) { 
        
        PersonalAccessToken.initialize(this, id, name, abilities, lastUsedAt, expiresAt, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, abilities, lastUsedAt, expiresAt, createdAt, updatedAt) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['abilities'] = abilities;
        obj['lastUsedAt'] = lastUsedAt;
        obj['expiresAt'] = expiresAt;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
    }

    /**
     * Constructs a <code>PersonalAccessToken</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday/GmodStore/Sdk/model/PersonalAccessToken} obj Optional instance to populate.
     * @return {module:Everyday/GmodStore/Sdk/model/PersonalAccessToken} The populated <code>PersonalAccessToken</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonalAccessToken();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('abilities')) {
                obj['abilities'] = ApiClient.convertToType(data['abilities'], [PersonalAccessTokenScope]);
            }
            if (data.hasOwnProperty('lastUsedAt')) {
                obj['lastUsedAt'] = ApiClient.convertToType(data['lastUsedAt'], 'Date');
            }
            if (data.hasOwnProperty('expiresAt')) {
                obj['expiresAt'] = ApiClient.convertToType(data['expiresAt'], 'Date');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
PersonalAccessToken.prototype['id'] = undefined;

/**
 * @member {String} name
 */
PersonalAccessToken.prototype['name'] = undefined;

/**
 * @member {Array.<module:Everyday/GmodStore/Sdk/model/PersonalAccessTokenScope>} abilities
 */
PersonalAccessToken.prototype['abilities'] = undefined;

/**
 * @member {Date} lastUsedAt
 */
PersonalAccessToken.prototype['lastUsedAt'] = undefined;

/**
 * @member {Date} expiresAt
 */
PersonalAccessToken.prototype['expiresAt'] = undefined;

/**
 * @member {Date} createdAt
 */
PersonalAccessToken.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
PersonalAccessToken.prototype['updatedAt'] = undefined;






export default PersonalAccessToken;

