/**
 * gmodstore
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # Rate limits Every request you make to the GmodStore API will count against your rate limit, which at the time of writing this, is 60 requests / minute. An up-to-date value will always provided in the `X-RateLimit-Limit` header The number of requests you have remaining before you must wait is provided in the `X-RateLimit-Remaining` header.  # API SDKs For a list of available API SDKs check the README here: https://github.com/everyday-as/gmodstore-api-docs#client-libraries
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductReviewVotes from './ProductReviewVotes';

/**
 * The ProductReview model module.
 * @module Everyday/GmodStore/Sdk/model/ProductReview
 * @version 3.0.0
 */
class ProductReview {
    /**
     * Constructs a new <code>ProductReview</code>.
     * @alias module:Everyday/GmodStore/Sdk/model/ProductReview
     * @param id {String} 
     * @param userId {String} 
     * @param title {String} 
     * @param body {String} 
     * @param rating {Number} 
     * @param version {String} 
     * @param votes {module:Everyday/GmodStore/Sdk/model/ProductReviewVotes} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     */
    constructor(id, userId, title, body, rating, version, votes, createdAt, updatedAt) { 
        
        ProductReview.initialize(this, id, userId, title, body, rating, version, votes, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, userId, title, body, rating, version, votes, createdAt, updatedAt) { 
        obj['id'] = id;
        obj['userId'] = userId;
        obj['title'] = title;
        obj['body'] = body;
        obj['rating'] = rating;
        obj['version'] = version;
        obj['votes'] = votes;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
    }

    /**
     * Constructs a <code>ProductReview</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday/GmodStore/Sdk/model/ProductReview} obj Optional instance to populate.
     * @return {module:Everyday/GmodStore/Sdk/model/ProductReview} The populated <code>ProductReview</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductReview();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('votes')) {
                obj['votes'] = ProductReviewVotes.constructFromObject(data['votes']);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ProductReview.prototype['id'] = undefined;

/**
 * @member {String} userId
 */
ProductReview.prototype['userId'] = undefined;

/**
 * @member {String} title
 */
ProductReview.prototype['title'] = undefined;

/**
 * @member {String} body
 */
ProductReview.prototype['body'] = undefined;

/**
 * @member {Number} rating
 */
ProductReview.prototype['rating'] = undefined;

/**
 * @member {String} version
 */
ProductReview.prototype['version'] = undefined;

/**
 * @member {module:Everyday/GmodStore/Sdk/model/ProductReviewVotes} votes
 */
ProductReview.prototype['votes'] = undefined;

/**
 * @member {Date} createdAt
 */
ProductReview.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
ProductReview.prototype['updatedAt'] = undefined;






export default ProductReview;

