/**
 * gmodstore
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # Rate limits Every request you make to the GmodStore API will count against your rate limit, which at the time of writing this, is 60 requests / minute. An up-to-date value will always provided in the `X-RateLimit-Limit` header The number of requests you have remaining before you must wait is provided in the `X-RateLimit-Remaining` header.  # API SDKs For a list of available API SDKs check the README here: https://github.com/everyday-as/gmodstore-api-docs#client-libraries
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductCoupon model module.
 * @module Everyday/GmodStore/Sdk/model/ProductCoupon
 * @version 3.1.0
 */
class ProductCoupon {
    /**
     * Constructs a new <code>ProductCoupon</code>.
     * @alias module:Everyday/GmodStore/Sdk/model/ProductCoupon
     * @param id {String} 
     * @param code {String} 
     * @param maxUses {Number} 
     * @param boundUser {String} 
     * @param expiresAt {Date} A future date less than 2 weeks from today
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     */
    constructor(id, code, maxUses, boundUser, expiresAt, createdAt, updatedAt) { 
        
        ProductCoupon.initialize(this, id, code, maxUses, boundUser, expiresAt, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, code, maxUses, boundUser, expiresAt, createdAt, updatedAt) { 
        obj['id'] = id;
        obj['code'] = code;
        obj['maxUses'] = maxUses;
        obj['boundUser'] = boundUser;
        obj['expiresAt'] = expiresAt;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
    }

    /**
     * Constructs a <code>ProductCoupon</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday/GmodStore/Sdk/model/ProductCoupon} obj Optional instance to populate.
     * @return {module:Everyday/GmodStore/Sdk/model/ProductCoupon} The populated <code>ProductCoupon</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductCoupon();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('percent')) {
                obj['percent'] = ApiClient.convertToType(data['percent'], 'Number');
            }
            if (data.hasOwnProperty('maxUses')) {
                obj['maxUses'] = ApiClient.convertToType(data['maxUses'], 'Number');
            }
            if (data.hasOwnProperty('boundUser')) {
                obj['boundUser'] = ApiClient.convertToType(data['boundUser'], 'String');
            }
            if (data.hasOwnProperty('expiresAt')) {
                obj['expiresAt'] = ApiClient.convertToType(data['expiresAt'], 'Date');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ProductCoupon.prototype['id'] = undefined;

/**
 * @member {String} code
 */
ProductCoupon.prototype['code'] = undefined;

/**
 * @member {Number} percent
 */
ProductCoupon.prototype['percent'] = undefined;

/**
 * @member {Number} maxUses
 */
ProductCoupon.prototype['maxUses'] = undefined;

/**
 * @member {String} boundUser
 */
ProductCoupon.prototype['boundUser'] = undefined;

/**
 * A future date less than 2 weeks from today
 * @member {Date} expiresAt
 */
ProductCoupon.prototype['expiresAt'] = undefined;

/**
 * @member {Date} createdAt
 */
ProductCoupon.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
ProductCoupon.prototype['updatedAt'] = undefined;






export default ProductCoupon;

