/**
 * gmodstore
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # Rate limits Every request you make to the GmodStore API will count against your rate limit, which at the time of writing this, is 60 requests / minute. An up-to-date value will always provided in the `X-RateLimit-Limit` header The number of requests you have remaining before you must wait is provided in the `X-RateLimit-Remaining` header.  # API SDKs For a list of available API SDKs check the README here: https://github.com/everyday-as/gmodstore-api-docs#client-libraries
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProductImages from './ProductImages';
import ProductPrice from './ProductPrice';

/**
 * The Product model module.
 * @module Everyday/GmodStore/Sdk/model/Product
 * @version 3.1.0
 */
class Product {
    /**
     * Constructs a new <code>Product</code>.
     * @alias module:Everyday/GmodStore/Sdk/model/Product
     * @param id {String} 
     * @param teamId {String} 
     * @param name {String} 
     * @param shortDescription {String} 
     * @param price {module:Everyday/GmodStore/Sdk/model/ProductPrice} 
     * @param images {module:Everyday/GmodStore/Sdk/model/ProductImages} 
     * @param views {Number} 
     * @param active {Boolean} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     */
    constructor(id, teamId, name, shortDescription, price, images, views, active, createdAt, updatedAt) { 
        
        Product.initialize(this, id, teamId, name, shortDescription, price, images, views, active, createdAt, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, teamId, name, shortDescription, price, images, views, active, createdAt, updatedAt) { 
        obj['id'] = id;
        obj['teamId'] = teamId;
        obj['name'] = name;
        obj['shortDescription'] = shortDescription;
        obj['price'] = price;
        obj['images'] = images;
        obj['views'] = views;
        obj['active'] = active;
        obj['createdAt'] = createdAt;
        obj['updatedAt'] = updatedAt;
    }

    /**
     * Constructs a <code>Product</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday/GmodStore/Sdk/model/Product} obj Optional instance to populate.
     * @return {module:Everyday/GmodStore/Sdk/model/Product} The populated <code>Product</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Product();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('teamId')) {
                obj['teamId'] = ApiClient.convertToType(data['teamId'], 'String');
            }
            if (data.hasOwnProperty('slug')) {
                obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('shortDescription')) {
                obj['shortDescription'] = ApiClient.convertToType(data['shortDescription'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ProductPrice.constructFromObject(data['price']);
            }
            if (data.hasOwnProperty('images')) {
                obj['images'] = ProductImages.constructFromObject(data['images']);
            }
            if (data.hasOwnProperty('views')) {
                obj['views'] = ApiClient.convertToType(data['views'], 'Number');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Product.prototype['id'] = undefined;

/**
 * @member {String} teamId
 */
Product.prototype['teamId'] = undefined;

/**
 * @member {String} slug
 */
Product.prototype['slug'] = undefined;

/**
 * @member {String} name
 */
Product.prototype['name'] = undefined;

/**
 * @member {String} shortDescription
 */
Product.prototype['shortDescription'] = undefined;

/**
 * @member {module:Everyday/GmodStore/Sdk/model/ProductPrice} price
 */
Product.prototype['price'] = undefined;

/**
 * @member {module:Everyday/GmodStore/Sdk/model/ProductImages} images
 */
Product.prototype['images'] = undefined;

/**
 * @member {Number} views
 */
Product.prototype['views'] = undefined;

/**
 * @member {Boolean} active
 */
Product.prototype['active'] = undefined;

/**
 * @member {Date} createdAt
 */
Product.prototype['createdAt'] = undefined;

/**
 * @member {Date} updatedAt
 */
Product.prototype['updatedAt'] = undefined;






export default Product;

