/**
 * GmodStore API
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TeamUser from './TeamUser';

/**
 * The Team model module.
 * @module Everyday/GmodStore/Sdk/model/Team
 * @version 1.2.0
 */
class Team {
    /**
     * Constructs a new <code>Team</code>.
     * @alias module:Everyday/GmodStore/Sdk/model/Team
     */
    constructor() { 
        
        Team.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Team</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday/GmodStore/Sdk/model/Team} obj Optional instance to populate.
     * @return {module:Everyday/GmodStore/Sdk/model/Team} The populated <code>Team</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Team();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('primaryAuthor')) {
                obj['primaryAuthor'] = TeamUser.constructFromObject(data['primaryAuthor']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Team.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Team.prototype['name'] = undefined;

/**
 * @member {Date} created_at
 */
Team.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
Team.prototype['updated_at'] = undefined;

/**
 * @member {module:Everyday/GmodStore/Sdk/model/TeamUser} primaryAuthor
 */
Team.prototype['primaryAuthor'] = undefined;






export default Team;

