/**
 * GmodStore API
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TeamUser from './TeamUser';

/**
 * The TeamUserListResponse model module.
 * @module Everyday/GmodStore/Sdk/model/TeamUserListResponse
 * @version 1.2.0
 */
class TeamUserListResponse {
    /**
     * Constructs a new <code>TeamUserListResponse</code>.
     * @alias module:Everyday/GmodStore/Sdk/model/TeamUserListResponse
     */
    constructor() { 
        
        TeamUserListResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TeamUserListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday/GmodStore/Sdk/model/TeamUserListResponse} obj Optional instance to populate.
     * @return {module:Everyday/GmodStore/Sdk/model/TeamUserListResponse} The populated <code>TeamUserListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeamUserListResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [TeamUser]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:Everyday/GmodStore/Sdk/model/TeamUser>} data
 */
TeamUserListResponse.prototype['data'] = undefined;






export default TeamUserListResponse;

