/**
 * gmodstore
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # Rate limits Every request you make to the GmodStore API will count against your rate limit, which at the time of writing this, is 60 requests / minute. An up-to-date value will always provided in the `X-RateLimit-Limit` header The number of requests you have remaining before you must wait is provided in the `X-RateLimit-Remaining` header.  # API SDKs For a list of available API SDKs check the README here: https://github.com/everyday-as/gmodstore-api-docs#client-libraries
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateProductCouponPayload model module.
 * @module Everyday/GmodStore/Sdk/model/UpdateProductCouponPayload
 * @version 3.0.0
 */
class UpdateProductCouponPayload {
    /**
     * Constructs a new <code>UpdateProductCouponPayload</code>.
     * @alias module:Everyday/GmodStore/Sdk/model/UpdateProductCouponPayload
     */
    constructor() { 
        
        UpdateProductCouponPayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateProductCouponPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday/GmodStore/Sdk/model/UpdateProductCouponPayload} obj Optional instance to populate.
     * @return {module:Everyday/GmodStore/Sdk/model/UpdateProductCouponPayload} The populated <code>UpdateProductCouponPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateProductCouponPayload();

            if (data.hasOwnProperty('percent')) {
                obj['percent'] = ApiClient.convertToType(data['percent'], 'Number');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('maxUses')) {
                obj['maxUses'] = ApiClient.convertToType(data['maxUses'], 'Number');
            }
            if (data.hasOwnProperty('expiresAt')) {
                obj['expiresAt'] = ApiClient.convertToType(data['expiresAt'], 'Date');
            }
            if (data.hasOwnProperty('boundUserId')) {
                obj['boundUserId'] = ApiClient.convertToType(data['boundUserId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} percent
 */
UpdateProductCouponPayload.prototype['percent'] = undefined;

/**
 * @member {String} code
 */
UpdateProductCouponPayload.prototype['code'] = undefined;

/**
 * @member {Number} maxUses
 */
UpdateProductCouponPayload.prototype['maxUses'] = undefined;

/**
 * @member {Date} expiresAt
 */
UpdateProductCouponPayload.prototype['expiresAt'] = undefined;

/**
 * @member {String} boundUserId
 */
UpdateProductCouponPayload.prototype['boundUserId'] = undefined;






export default UpdateProductCouponPayload;

