/**
 * gmodstore
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # Rate limits Every request you make to the GmodStore API will count against your rate limit, which at the time of writing this, is 60 requests / minute. An up-to-date value will always provided in the `X-RateLimit-Limit` header The number of requests you have remaining before you must wait is provided in the `X-RateLimit-Remaining` header.  # API SDKs For a list of available API SDKs check the README here: https://github.com/everyday-as/gmodstore-api-docs#client-libraries
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserBan model module.
 * @module Everyday/GmodStore/Sdk/model/UserBan
 * @version 3.1.0
 */
class UserBan {
    /**
     * Constructs a new <code>UserBan</code>.
     * @alias module:Everyday/GmodStore/Sdk/model/UserBan
     * @param id {String} 
     * @param userId {String} 
     * @param properties {Array.<module:Everyday/GmodStore/Sdk/model/UserBan.PropertiesEnum>} 
     * @param start {Date} 
     * @param end {Date} 
     */
    constructor(id, userId, properties, start, end) { 
        
        UserBan.initialize(this, id, userId, properties, start, end);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, userId, properties, start, end) { 
        obj['id'] = id;
        obj['userId'] = userId;
        obj['properties'] = properties;
        obj['start'] = start;
        obj['end'] = end;
    }

    /**
     * Constructs a <code>UserBan</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday/GmodStore/Sdk/model/UserBan} obj Optional instance to populate.
     * @return {module:Everyday/GmodStore/Sdk/model/UserBan} The populated <code>UserBan</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserBan();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('bannerId')) {
                obj['bannerId'] = ApiClient.convertToType(data['bannerId'], 'String');
            }
            if (data.hasOwnProperty('unbanId')) {
                obj['unbanId'] = ApiClient.convertToType(data['unbanId'], 'String');
            }
            if (data.hasOwnProperty('unbanReason')) {
                obj['unbanReason'] = ApiClient.convertToType(data['unbanReason'], 'String');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], ['String']);
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'Date');
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = ApiClient.convertToType(data['end'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
UserBan.prototype['id'] = undefined;

/**
 * @member {String} userId
 */
UserBan.prototype['userId'] = undefined;

/**
 * @member {String} reason
 */
UserBan.prototype['reason'] = undefined;

/**
 * @member {String} bannerId
 */
UserBan.prototype['bannerId'] = undefined;

/**
 * @member {String} unbanId
 */
UserBan.prototype['unbanId'] = undefined;

/**
 * @member {String} unbanReason
 */
UserBan.prototype['unbanReason'] = undefined;

/**
 * @member {Array.<module:Everyday/GmodStore/Sdk/model/UserBan.PropertiesEnum>} properties
 */
UserBan.prototype['properties'] = undefined;

/**
 * @member {Date} start
 */
UserBan.prototype['start'] = undefined;

/**
 * @member {Date} end
 */
UserBan.prototype['end'] = undefined;





/**
 * Allowed values for the <code>properties</code> property.
 * @enum {String}
 * @readonly
 */
UserBan['PropertiesEnum'] = {

    /**
     * value: "everything"
     * @const
     */
    "everything": "everything",

    /**
     * value: "addon.create"
     * @const
     */
    "addon.create": "addon.create",

    /**
     * value: "addon.purchase"
     * @const
     */
    "addon.purchase": "addon.purchase",

    /**
     * value: "addon.download"
     * @const
     */
    "addon.download": "addon.download",

    /**
     * value: "addon.review"
     * @const
     */
    "addon.review": "addon.review",

    /**
     * value: "addon.comment"
     * @const
     */
    "addon.comment": "addon.comment",

    /**
     * value: "job.create"
     * @const
     */
    "job.create": "job.create",

    /**
     * value: "job.apply"
     * @const
     */
    "job.apply": "job.apply",

    /**
     * value: "job.review"
     * @const
     */
    "job.review": "job.review",

    /**
     * value: "job.comment"
     * @const
     */
    "job.comment": "job.comment",

    /**
     * value: "forum.post"
     * @const
     */
    "forum.post": "forum.post",

    /**
     * value: "ban.appeal"
     * @const
     */
    "ban.appeal": "ban.appeal"
};



export default UserBan;

