/**
 * gmodstore
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.  # Rate limits Every request you make to the GmodStore API will count against your rate limit, which at the time of writing this, is 60 requests / minute. An up-to-date value will always provided in the `X-RateLimit-Limit` header The number of requests you have remaining before you must wait is provided in the `X-RateLimit-Remaining` header.  # API SDKs For a list of available API SDKs check the README here: https://github.com/everyday-as/gmodstore-api-docs#client-libraries
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The User model module.
 * @module Everyday/GmodStore/Sdk/model/User
 * @version 3.1.0
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * @alias module:Everyday/GmodStore/Sdk/model/User
     * @param id {String} 
     * @param steamId {Number} 
     * @param name {String} 
     * @param avatar {String} 
     * @param bio {String} 
     * @param lastActionAt {Date} 
     * @param createdAt {Date} 
     */
    constructor(id, steamId, name, avatar, bio, lastActionAt, createdAt) { 
        
        User.initialize(this, id, steamId, name, avatar, bio, lastActionAt, createdAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, steamId, name, avatar, bio, lastActionAt, createdAt) { 
        obj['id'] = id;
        obj['steamId'] = steamId;
        obj['name'] = name;
        obj['avatar'] = avatar;
        obj['bio'] = bio;
        obj['lastActionAt'] = lastActionAt;
        obj['createdAt'] = createdAt;
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday/GmodStore/Sdk/model/User} obj Optional instance to populate.
     * @return {module:Everyday/GmodStore/Sdk/model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('steamId')) {
                obj['steamId'] = ApiClient.convertToType(data['steamId'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
            }
            if (data.hasOwnProperty('bio')) {
                obj['bio'] = ApiClient.convertToType(data['bio'], 'String');
            }
            if (data.hasOwnProperty('lastActionAt')) {
                obj['lastActionAt'] = ApiClient.convertToType(data['lastActionAt'], 'Date');
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('teamsCount')) {
                obj['teamsCount'] = ApiClient.convertToType(data['teamsCount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
User.prototype['id'] = undefined;

/**
 * @member {Number} steamId
 */
User.prototype['steamId'] = undefined;

/**
 * @member {String} name
 */
User.prototype['name'] = undefined;

/**
 * @member {String} email
 */
User.prototype['email'] = undefined;

/**
 * @member {String} avatar
 */
User.prototype['avatar'] = undefined;

/**
 * @member {String} bio
 */
User.prototype['bio'] = undefined;

/**
 * @member {Date} lastActionAt
 */
User.prototype['lastActionAt'] = undefined;

/**
 * @member {Date} createdAt
 */
User.prototype['createdAt'] = undefined;

/**
 * @member {Number} teamsCount
 */
User.prototype['teamsCount'] = undefined;






export default User;

