/**
 * GmodStore API
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserBadgeLegend model module.
 * @module Everyday/GmodStore/Sdk/model/UserBadgeLegend
 * @version 1.1.0
 */
class UserBadgeLegend {
    /**
     * Constructs a new <code>UserBadgeLegend</code>.
     * @alias module:Everyday/GmodStore/Sdk/model/UserBadgeLegend
     */
    constructor() { 
        
        UserBadgeLegend.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserBadgeLegend</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday/GmodStore/Sdk/model/UserBadgeLegend} obj Optional instance to populate.
     * @return {module:Everyday/GmodStore/Sdk/model/UserBadgeLegend} The populated <code>UserBadgeLegend</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserBadgeLegend();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('ext')) {
                obj['ext'] = ApiClient.convertToType(data['ext'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
UserBadgeLegend.prototype['id'] = undefined;

/**
 * @member {String} name
 */
UserBadgeLegend.prototype['name'] = undefined;

/**
 * @member {String} description
 */
UserBadgeLegend.prototype['description'] = undefined;

/**
 * @member {String} ext
 */
UserBadgeLegend.prototype['ext'] = undefined;






export default UserBadgeLegend;

