/**
 * GmodStore API
 * Welcome to the GmodStore API! You can use our API to access GmodStore API endpoints, which can be used interact with GmodStore programmatically.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserBan from './UserBan';

/**
 * The UserBanListResponse model module.
 * @module Everyday\GmodStore\Sdk/model/UserBanListResponse
 * @version 1.0.1
 */
class UserBanListResponse {
    /**
     * Constructs a new <code>UserBanListResponse</code>.
     * @alias module:Everyday\GmodStore\Sdk/model/UserBanListResponse
     */
    constructor() { 
        
        UserBanListResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserBanListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Everyday\GmodStore\Sdk/model/UserBanListResponse} obj Optional instance to populate.
     * @return {module:Everyday\GmodStore\Sdk/model/UserBanListResponse} The populated <code>UserBanListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserBanListResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [UserBan]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:Everyday\GmodStore\Sdk/model/UserBan>} data
 */
UserBanListResponse.prototype['data'] = undefined;






export default UserBanListResponse;

